backend/models/Schedule.php
<?php

namespace app\models;

use app\modules\reserves\models\Reserve;
use app\modules\rooms\models\Room;
use app\modules\bands\models\Band;
use Yii;

/**
 * This is the model class for table "schedule".
 *
 * @property integer $id
 * @property integer $room_id
 * @property integer $reserve_id
 * @property integer $band_id
 * @property integer $timestamp
 */
class Schedule extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'schedule';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'room_id', 'reserve_id', 'band_id', 'timestamp'], 'integer']
        ];
    }

    public function getReserve()
    {
        return $this->hasOne(Reserve::className(), ['id' => 'reserve_id']);
    }

    public function getRoom()
    {
        return $this->hasOne(Room::className(), ['id' => 'room_id']);
    }

    public function getBand()
    {
        return $this->hasOne(Band::className(), ['id' => 'band_id']);
    }

    public function getBrothers(){
        $dayStart = strtotime(date('d.m.Y',$this->timestamp));
        $dayEnd = $dayStart+24*60*60;
        return Schedule::find()->where('timestamp >= :dayStart AND timestamp < :dayEnd AND reserve_id = :reserveID',[':dayStart'=>$dayStart,':dayEnd'=>$dayEnd,':reserveID'=>$this->reserve_id])
            ->orderBy(['timestamp'=>SORT_ASC]);
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'room_id' => 'Room ID',
            'reserve_id' => 'Reserve ID',
            'band_id' => 'Band ID',
            'timestamp' => 'Timestamp',
        ];
    }
}

backend/controllers/ScheduleController.php
<?php

namespace backend\controllers;

use app\models\Schedule;
use Yii;
use app\modules\reserves\models\Reserve;
use app\modules\rooms\models\Room;
use yii\web\ForbiddenHttpException;
use app\components\AjaxController;

class ScheduleController extends AjaxController
{


    public function actionIndex()
    {
        $this->layout = 'schedule';

        if (!Yii::$app->user->can('viewTable')) {
            throw new ForbiddenHttpException('Access denied');
        }
        $params = Yii::$app->request->post();


        if (isset($params['room_id']) && $params['room_id'] > 0):
            Yii::$app->session->set('schedule_room_id', $params['room_id']);
        elseif (isset($params['room_id']) && $params['room_id'] == 0):
            Yii::$app->session->destroy('schedule_room_id');
        endif;
        if (Yii::$app->session->has('schedule_room_id')) {
            $rooms = Room::findAll(Yii::$app->session->get('schedule_room_id'));
        } else {
            $rooms = Room::find()->all();
        }

        if (isset($params['long']) && $params['long'] > 0):
            Yii::$app->session->set('schedule_long', $params['long']);
        endif;
        Yii::$app->session->has('schedule_long') ? $long = Yii::$app->session->get('schedule_long') : $long = 7;

        if (isset($params['date']) && $params['date'] > 0):
            Yii::$app->session->set('schedule_start', $params['date']);
        endif;
        if (Yii::$app->session->has('schedule_start')) {
            $start = new \Datetime(Yii::$app->session->get('schedule_start'));
            $startDate = new \Datetime(Yii::$app->session->get('schedule_start'));
        } else {
            $d = new \Datetime();
            $d->setTime(0, 0, 0);
            $start = $d;
            $startDate = $d;
        }

        $end = new \Datetime($start->format('Y-m-d H:i:s'));
        $end->modify('+' . $long . ' day');

        if (isset($params['band_id']) && $params['band_id'] > 0):
            Yii::$app->session->set('schedule_band_id', $params['band_id']);
        endif;
        $band_id = Yii::$app->session->has('schedule_band_id') ? Yii::$app->session->get('schedule_band_id') : false;


        $params = ['rooms' => $rooms, 'startDate' => $startDate, 'long' => $long, 'start' => $start, 'end' => $end, 'reserves' => Reserve::getActiveReserves($start, $end, $band_id)];
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax('index', $params);
        } else {
            return $this->render('index', $params);
        }
    }

    public function actionCell($id, $date)
    {
        $model = Reserve::findOne($id);
        $scheduleTimestamp = new \DateTime($date . ' ' . $model->start_hour . ':00');
        $schedule = $model->getSchedule()->where(['timestamp' => $scheduleTimestamp->format('U')])->one();
        return $this->renderPartial('_more_info.php', ['model' => $model, 'schedule' => $schedule]);
    }

    public function actionUpdate($offset = 0, $limit = 300)
    {
        $reserves = Reserve::find()->offset($offset)->limit($limit)->all();
        if (count($reserves) > 0) {
            foreach ($reserves as $reserve) {
                $timestamps = json_decode($reserve->data);
                $newdata = [];
                if (is_array($timestamps)) {
                    foreach ($timestamps as $t => $timestamp) {
                        $newdata[$t + 3600] = $timestamp;
                    }
                } else {
                    Yii::$app->session->set('bad_reserves', Yii::$app->session->get('bad_reserves') . ' ' . $reserve->id);
                }
                $reserve->data = json_encode($newdata);
                $reserve->save();
            }
            $this->redirect('/schedule/update?offset=' . ($offset + $limit));
        } else {
            echo 'Ok';
            var_dump(Yii::$app->session->get('bad_reserves'));
        }


    }
}

backend/views/schedule/_cell.php
<?
use kartik\icons\Icon;
Icon::map($this,Icon::EL);
Icon::map($this,Icon::FA);
?>

<td
    class="hour reserved<?=$model->isDayDay()?' dayday':''?>"
    title="<?=$model->band->title;?> "
    data-hour="0"
    data-reserve="<?=$model->id;?>"
    data-date="<?=$startDate->format('d.m.Y');?>"
    data-room="<?=$model->room->id;?>"
    data-price="<?=$model->room->price;?>"
    data-band="<?=$model->band->id;?>"
<?if(!$model->is_night):?>
    colspan="<?=$model->hours;?> "
<?endif;?>
    style="background:<?=$model->room->color;?>">
    <a href="<?=Yii::$app->user->can('createReserve')?'/reserves/default/detail?id='.$model->id:'#';?>" class="reserved-cell">
        <span class="band-title">
            <?=$model->band->title;?>
        </span>
        <?if(Yii::$app->user->can('create')):?>
            <?=$model->summary_payment >= $model->summary_price ? Icon::show('rub', ['class' => 'pull-right','title'=>'Оплачено']) : '';?>
            <?=$model->getWeeks() > 1 && (int)date('U',strtotime($model->end)) > (int)$startDate->format('U') ? Icon::show('calendar', ['class' => 'pull-right','title'=>'Постоянка']):'';?>
            <?=$model->getWeeks() > 1 && (int)date('U',strtotime($model->end)) == (int)date('U',strtotime($startDate->format('d.m.Y'))) ? Icon::show('calendar-o', ['class' => 'pull-right','title'=>'Конец постоянки']):'';?>
            <?=$model->band->debt > 0 ? Icon::show('exclamation', ['class' => 'pull-right color-red','title'=>'Долг!']) : '';?>
            <?foreach($model->services as $service):?> 
                <?=$service->icon?Icon::show($service->icon, ['class' => 'pull-right','title'=>$service->title],Icon::EL):'';?>
            <?endforeach;?>
        <?endif;?>
    </a>

    <?if(Yii::$app->user->can('create')):?>
    <div class="more-info">
    </div>
    <?endif;?>
</td>

backend/views/schedule/_filter.php
<?
use yii\helpers\ArrayHelper;
use app\modules\rooms\models\Room;
use kartik\widgets\Select2;
use yii\web\JsExpression;
$url = \yii\helpers\Url::to(['/bands/default/json']);
$urlService = \yii\helpers\Url::to(['/services/default/json']);
$initScript = <<< SCRIPT
function (element, callback) {
    var id=\$(element).val();
    if (id !== "") {
        \$.ajax("{$url}?id=" + id, {
            dataType: "json"
        }).done(function(data) { callback(data.results);});
    }
}
SCRIPT;
$initScriptService = <<< SCRIPT
function (element, callback) {
    var id=\$('#reserve-room_id').val();
    if (id !== "") {
        \$.ajax("{$urlService}?room_id=" + id, {
            dataType: "json"
        }).done(function(data) { callback(data.results);});
    }
}
SCRIPT;
?>
<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation" id="scheduleFilter">
    <div class="container-fluid text-right">
        <form class="navbar-form" role="form" action="/schedule" id="filter">
            <div class="form-group">
                <?= \yii\helpers\Html::dropdownList('long', Yii::$app->session->get('schedule_long'), [0 => 'По времени', 1 => 'День', 3 => '3 дня', 7 => 'Неделя', 14 => '2 недели', 30 => 'месяц'], ['class' => 'form-control', 'empty' => 'По времени']) ?>
            </div>
            <div class="form-group">
                <?=
                \yii\jui\DatePicker::widget([
                    'name' => 'date',
                    'language' => 'ru',
                    'value'=>Yii::$app->session->get('schedule_start'),
                    'dateFormat'=> 'dd.MM.yyyy',
                    'options' => ['placeholder' => 'Начальная дата', 'class' => 'form-control', 'size'=>'10']
                ])?>
            </div>
            <div class="form-group">
            <?
                $roomsArray = ArrayHelper::map(Room::find()->all(), 'id', 'title');
                array_unshift($roomsArray, 'Все комнаты');
                echo \yii\helpers\Html::dropdownList('room_id', Yii::$app->session->get('schedule_room_id'), $roomsArray, ['class' => 'form-control', 'empty' => 'По комнате']);
            ?>
                </div>
            <div class="form-group pull-left">
            <?=
            Select2::widget([
                'data' => yii\helpers\ArrayHelper::map(\app\modules\bands\models\Band::find()->all(), 'id', 'title'),
                'options' => ['placeholder' => 'Укажите название группы ...'],
                'name' => 'band_id',
                'value' => Yii::$app->session->has('schedule_band_id')?Yii::$app->session->get('schedule_band_id'):'',
                'pluginOptions' => [
                    'allowClear' => true,
                    'ajax' => [
                        'url' => $url,
                        'dataType' => 'json',
                        'data' => new JsExpression('function(term,page) { return {search:term}; }'),
                        'results' => new JsExpression('function(data,page) { return {results:data.results}; }'),
                    ],
                    'initSelection' => new JsExpression($initScript)
                ],
            ])
            ?>
                </div>
        </form>
    </div>
</nav>

backend/views/schedule/_more_info.php
<?
/**
 * @var $model app\modules\reserves\models\Reserve
 * @var $schedule app\models\Schedule
 */
use kartik\icons\Icon;
use yii\helpers\Html;
Icon::map($this,Icon::EL);
Icon::map($this,Icon::FA);
?>
<?=Icon::show('times',['class'=>'close'],Icon::FA);?>
    <h5><a href="/reserves/default/detail?id=<?=$model->id?>">Резерв №<?=$model->id?></a>
    <?if(Yii::$app->user->can('underCall')):?>
        &nbsp;&nbsp;&nbsp;<a href="/reserves/default/update?id=<?=$model->id?>" class="small"><?=Icon::show('edit')?></a>
    <?endif;?>
    </h5>
    <p><strong>Стоимость:</strong> <?=$model->summary_price?> руб.</p>
<?if(isset($model->discount)):?>
    <p><strong>Скидка:</strong> <?=$model->discount->value?> <?=$model->discount->type == 1?'руб.':'%'?></p>
<?endif;?>
    <p><strong>Оплачено:</strong> <?=$model->summary_payment?> руб.</p>
<?if($model->getWeeks() > 1):?>
    <br />
    <p><strong>Постоянка:</strong> <?=$model->getWeeks()?> недель</p>
    <p>c <?=date('d.m.Y',strtotime($model->start))?> до <?=date('d.m.Y',strtotime($model->end))?></p>
<?endif;?>
    <br />
    <p><strong>Зарезервирован:</strong> <?=date('H:i d.m.Y',$model->created_at)?></p>
    <p><strong>Пользователем:</strong> <?=Html::a(\backend\modules\users\models\User::findOne($model->user_create)->username,['/users/manage/view','id'=>$model->user_create]);?></p>
<?if(isset($model->updated_at)):?>
    <p><strong>Обновлен:</strong> <?=date('H:i d.m.Y',$model->updated_at)?></p>
<?endif;?>
    <br />
    <p><strong>Клиент:</strong> <?=Html::a($model->band->title,['/bands/default/view','id'=>$model->band->id])?></p>
<?if($model->band->debt):?>
    <p class="color-red"><strong>Долг:</strong> <?=$model->band->debt?> руб.</p>
<?endif;?>
<?if($model->band->getFined()->count() > 0):?>
    <?foreach($model->band->getFined()->all() as $reserve):?>
        <p><strong>Штраф:</strong> <a href="<?=$reserve->getUrl()?>">от <?=$reserve->start?> <?=$reserve->room->title?> <?=$reserve->start_hour?>:00 <?=$reserve->calculateFine()?> р.</a></p>
    <?endforeach;?>
<?endif;?>
<?if(isset($model->services)&&count($model->services)>0):?>
    <br />
    <h5>Доп. услуги</h5>
    <table class="table">
        <?foreach($model->services as $service):?>
            <tr><td><strong><?=$service->title?>:</strong></td><td class="col-xs-4"><?=$service->price?> <?=$service->units?></td></tr>
        <?endforeach;?>
    </table>
<?endif;?>
    <hr />
    <div class="row">
        <?if(Yii::$app->user->can('underCall')):?>
            <div class="col-xs-6">
                <?= $model->needPay() > 0 ? Html::a('Оплатить', ['/reserves/default/payment', 'id' => $model->id], ['class' => 'btn btn-success btn-sm']):'' ?>
            </div>
        <?endif;?>
        <div class="col-xs-6 text-right">
        <?if($model->getWeeks() > 1):?>

            <?= Html::a('Удалить', ['/reserves/default/day', 'id' => $schedule->id], [
                'class' => 'btn btn-danger btn-sm',
                'data' => [
                    'confirm' => 'Уверены что хотите удалить день из постоянки?',
                    'method' => 'post',
                ],
            ]) ?>
        <?else:?>
            <?= Html::a('Удалить', ['/reserves/default/remove', 'id' => $model->id], [
                'class' => 'btn btn-danger btn-sm',
                'data' => [
                    'confirm' => 'Уверены что хотите удалить позицию?',
                    'method' => 'post',
                ],
            ]) ?>
        <?endif;?>
        </div>
    </div>
<?if($model->isActual()):?>
    <br />
    <div class="row">
        <div class="col-xs-12">
        <?if($model->getWeeks() > 1):?>
            <?=Html::a('Отменить бронь', ['/reserves/default/daycancel', 'id' => $schedule->id], ['class' => 'btn btn-warning  btn-sm btn-block', 'data'=> ['confirm'=>'Если резерв будет отменен менее чем за 48 часов. Штраф +50%: '.$model->calculateFine().' руб. Действительно отменить?']])?>
        <?else:?>
            <?=Html::a('Отменить бронь', ['/reserves/default/cancel', 'id' => $model->id], ['class' => 'btn btn-warning  btn-sm btn-block', 'data'=> ['confirm'=>'Если резерв будет отменен менее чем за 48 часов. Штраф +50%: '.$model->calculateFine().' руб. Действительно отменить?']])?>
        <?endif;?>
        </div>
    </div>
<?endif;?>

backend/views/schedule/index.php
<?php
/* @var $this yii\web\View */
use common\components\Days;
use app\modules\reserves\models\Reserve;
$this->title = 'Расписание';
\backend\assets\ScheduleAsset::register($this);
?>

<table class="table table-bordered schedule-body">
    <thead>
    <tr>
        <th class="date">Дата</th>
        <th class="title">Комнаты</th>
        <th class="hour night">Ночь</th>
        <? for ($i = 9; $i <= 23; $i++): ?>
            <th class="hour <?=$i%3==0?'setStart':''?>"><?= $i ?>:00</th>
        <? endfor; ?>
    </tr>
    </thead>
    <tbody>
    <? for ($d = 0; $d <= ($long - 1); $d++): ?>
        <? $d > 0 ? $startDate->modify('+1 day') : ''; ?>
        <? foreach ($rooms as $k => $room): ?>
            <tr<?= $room == end($rooms) ? ' class="last"' : '' ?>>
                <? if ($k == 0): ?>
                    <td class="date<?=Days::isWeekend($startDate->format('d.m.Y'))?' weekend':''?>" rowspan="<?= count($rooms) ?>">
                        <span class="week-day<?=date('Ymd') == date('Ymd', $startDate->format('U'))?' today':''?>"><?= Days::dayOfWeek($startDate) ?></span>
                        <?= $startDate->format('d.m.Y'); ?>
                    </td>
                <? endif; ?>
                <td class="title"><?= $room->title ?><span class="price"><?=$room->price?> руб.</span></td>
                <!-- RESERVES -->
                <?
                $timestamp = strtotime($startDate->format('d.m.Y') . ' ' . 0 . ':00');
                if(isset ($reserves[$timestamp][$room->id])):
                    echo $this->render('_cell',[
                        'model'=>Reserve::findOne($reserves[$timestamp][$room->id]['reserve_id']),
                        'startDate'=>$startDate,
                    ]);
                else:?>
                    <td class="hour empty night"
                        data-hour="0"
                        data-date="<?= $startDate->format('d.m.Y'); ?>" data-room="<?= $room->id ?>"
                        data-price="<?= $room->price ?>">
                    </td>
                <?
                endif;
                $activeHours = 0;
                for ($i = 9; $i <= 23; $i++):
                    if ($activeHours > 0):
                        $activeHours--;
                    else:
                        $timestamp = strtotime($startDate->format('d.m.Y') . ' ' . $i . ':00');
                        if (isset ($reserves[$timestamp][$room->id])):
                            $reserve = Reserve::findOne($reserves[$timestamp][$room->id]['reserve_id']);
                            $activeHours = $reserve->hours - 1;
                            echo $this->render('_cell',[
                                'model'=>$reserve,
                                'startDate'=>$startDate,
                                'timestamp'=>$timestamp
                            ]);

                        else: ?>
                            <td class="hour empty <?=$i%3==0?'setStart':''?>"
                                data-hour="<?= $i ?>"
                                data-date="<?= $startDate->format('d.m.Y'); ?>" data-room="<?= $room->id ?>"
                                data-price="<?= $room->price ?>"></td>
                        <?endif; ?>
                    <?endif; ?>
                <? endfor; ?>
            </tr>
        <? endforeach; ?>
    <? endfor; ?>
    </tbody>
</table>
<?